# Generated by Django 2.0.2 on 2018-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('line_name', models.CharField(max_length=20)),
                ('direction', models.BooleanField()),
                ('bus_stop_id', models.IntegerField()),
                ('bus_stop_name', models.CharField(max_length=17)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
    ]
