# Generated by Django 2.0.2 on 2018-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineinfo', '0002_busline_line_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busid', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=8)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
