# Generated by Django 2.0.2 on 2018-02-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineinfo', '0003_bus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='busid',
            new_name='bus_id',
        ),
    ]
