# Generated by Django 2.0.2 on 2018-02-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineinfo', '0004_auto_20180207_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_id',
        ),
    ]
