# Generated by Django 2.0.2 on 2018-04-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineinfo', '0005_remove_bus_bus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdBusFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('line_id', models.IntegerField()),
                ('bus_stop_id', models.IntegerField()),
                ('passengers_in', models.IntegerField()),
                ('passengers_out', models.IntegerField()),
                ('passengers_total', models.IntegerField()),
                ('expected_arrival', models.DateField()),
                ('arrival_time', models.DateField()),
                ('departure_time', models.DateField()),
            ],
        ),
    ]
