# Generated by Django 2.0.2 on 2018-04-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineinfo', '0006_updbusfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updbusfeed',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='updbusfeed',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='updbusfeed',
            name='expected_arrival',
            field=models.TimeField(),
        ),
    ]
